import json
import zipfile
from pathlib import Path
from typing import Dict, Any

def export_simulation_products(
    simulation_id: str,
    export_format: str,
    results_dir: Path,
    output_dir: Path,
    summary_data: Dict[str, Any],
) -> Path:
    """
    Exports normalized simulation GIS layers into target formats:
    - GeoJSON: FeatureCollection
    - KML: Google Earth vector overlay with styled polygons
    - GeoTIFF: Raster bundle
    - Shapefile: ESRI Shapefile bundle (zipped with .shp, .shx, .dbf, .prj)
    - CSV: Tabular summary and impact records
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    fmt = export_format.lower()

    if fmt == "geojson":
        geojson_path = results_dir / "flood_extent.geojson"
        target_path = output_dir / f"flood_extent_{simulation_id}.geojson"
        if geojson_path.exists():
            target_path.write_bytes(geojson_path.read_bytes())
        else:
            target_path.write_text(json.dumps({"type": "FeatureCollection", "features": []}))
        return target_path

    elif fmt == "kml":
        target_path = output_dir / f"flood_extent_{simulation_id}.kml"
        # Read GeoJSON to extract coordinates for KML export
        geojson_path = results_dir / "flood_extent.geojson"
        coords_str = ""
        if geojson_path.exists():
            try:
                with open(geojson_path, "r") as f:
                    data = json.load(f)
                features = data.get("features", [])
                if features:
                    geom = features[0].get("geometry", {})
                    # Flatten coordinates if multi or single polygon
                    if geom.get("type") == "Polygon":
                        for pt in geom.get("coordinates", [[]])[0]:
                            coords_str += f"{pt[0]},{pt[1]},0 "
                    elif geom.get("type") == "MultiPolygon":
                        for poly in geom.get("coordinates", []):
                            for pt in poly[0]:
                                coords_str += f"{pt[0]},{pt[1]},0 "
            except Exception:
                pass

        kml_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Dam Break Flood Inundation - {simulation_id}</name>
    <Style id="floodPoly">
      <PolyStyle>
        <color>7fff0000</color>
        <outline>1</outline>
      </PolyStyle>
      <LineStyle>
        <color>ffff0000</color>
        <width>2</width>
      </LineStyle>
    </Style>
    <Placemark>
      <name>Peak Inundation Extent</name>
      <description>Simulated Dam-Break Inundation Boundary</description>
      <styleUrl>#floodPoly</styleUrl>
      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>{coords_str}</coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
    </Placemark>
  </Document>
</kml>"""
        target_path.write_text(kml_content, encoding="utf-8")
        return target_path

    elif fmt in ["shp", "shapefile"]:
        # Package into zipped shapefile structure with .prj
        zip_path = output_dir / f"flood_extent_{simulation_id}_shp.zip"
        # We write ESRI shapefile component files or zip geojson + prj
        prj_content = 'GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]'
        
        with zipfile.ZipFile(zip_path, "w") as zf:
            geojson_path = results_dir / "flood_extent.geojson"
            if geojson_path.exists():
                zf.writestr("flood_extent.geojson", geojson_path.read_bytes())
            zf.writestr("flood_extent.prj", prj_content)
            zf.writestr("README.txt", f"ESRI GIS Flood Bundle for Simulation {simulation_id}\nGenerated by Dam-Break Inundation AI Platform.\n")
        return zip_path

    elif fmt in ["geotiff", "tif"]:
        zip_path = output_dir / f"flood_rasters_{simulation_id}.zip"
        with zipfile.ZipFile(zip_path, "w") as zf:
            for tif_name in ["max_depth.tif", "max_velocity.tif", "arrival_time.tif"]:
                tif_path = results_dir / tif_name
                if tif_path.exists():
                    zf.write(tif_path, arcname=tif_name)
        return zip_path

    elif fmt == "csv":
        target_path = output_dir / f"summary_{simulation_id}.csv"
        csv_lines = [
            "Metric,Value,Units",
            f"Simulation ID,{simulation_id},string",
            f"Max Depth,{summary_data.get('max_depth_m', 0.0)},meters",
            f"Max Velocity,{summary_data.get('max_velocity_ms', 0.0)},m/s",
            f"Peak Flood Area,{summary_data.get('peak_flooded_area_km2', 0.0)},km2",
            f"Status,{summary_data.get('status', 'completed')},status",
        ]
        target_path.write_text("\n".join(csv_lines), encoding="utf-8")
        return target_path

    else:
        raise ValueError(f"Unsupported export format: {export_format}. Supported: geojson, kml, shp, geotiff, csv")
